AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  taxi-coop

  Sample SAM Template for taxi-coop

Parameters:
  SouthWest:
    Type: String
    Default: 12.8,77.5
  NorthEast:
    Type: String
    Default: 13.5,78.2
  DBUser:
    Type: String
    Description: Document DB User
    Default: taxi
  DBPass:
    Type: String
    Description: Document DB Password
    Default: taxi1234
  DBEndPoint:
    Type: String
    Description: Document DB Endpoint
    Default: My Endpoint
  DBSecurityGroups:
    Type: CommaDelimitedList
    Description: Security Groupd Ids of DB Cluster VPC
  DBSubnets:
    Type: CommaDelimitedList
    Description: Subnets in DB Cluster VPC
  RegisterLambdaArn:
    Type: String
    Description: Arn of Lambda Function for Taxi Registration in DB
  IoTPolicy:
    Type: String
    Description: IoT Policy
    Default: Taxi_policy
  IoTThingType:
    Type: String
    Description: IoT Thing Type
    Default: TAXI
  IoTThingGroup:
    Type: String
    Description: IoT Thing Group
    Default: Taxi_group

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        SOUTHWEST: !Ref SouthWest
        NORTHEAST: !Ref NorthEast

Resources:
  TCGeocoderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tc_geocoder/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        TCGeocoder:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /geocoder
            Method: any

  TCDirectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tc_directions/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        TCDirections:
          Type: Api
          Properties:
            Path: /directions
            Method: any

  TCRegisterTaxiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tc_register_taxi/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          register_lambda_arn: !Ref RegisterLambdaArn
          iot_policy: !Ref IoTPolicy
          iot_thing_type: !Ref IoTThingType
          iot_thing_group: !Ref IoTThingGroup
      Policies:
        - AWSIoTFullAccess
        - Version: '2012-10-17'
          Statement:
          - Sid: LambdaInvokePolicy
            Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:InvokeAsync
            Resource: !Ref RegisterLambdaArn
      Events:
        TCDirections:
          Type: Api
          Properties:
            Path: /register_taxi
            Method: post

  TCTaxisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tc_taxis/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          db_user: !Ref DBUser
          db_pass: !Ref DBPass
          db_endpoint: !Ref DBEndPoint
      VpcConfig:
          SecurityGroupIds: !Ref DBSecurityGroups
          SubnetIds: !Ref DBSubnets
      Events:
        TCGetTaxis:
          Type: Api
          Properties:
            Path: /taxi
            Method: get
        TCGetTaxi:
          Type: Api
          Properties:
            Path: /taxi/{id}
            Method: get
        TCPostTaxi:
          Type: Api
          Properties:
            Path: /taxi/{id}
            Method: post
          TCDeleteTaxi:
            Type: Api
            Properties:
              Path: /taxi/{id}
              Method: delete
          TCPatchUsers:
            Type: Api
            Properties:
              Path: /taxi/{id}
              Method: patch


  TCRequestRideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tc_request_ride/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          db_user: !Ref DBUser
          db_pass: !Ref DBPass
          db_endpoint: !Ref DBEndPoint
      VpcConfig:
          SecurityGroupIds: !Ref DBSecurityGroups
          SubnetIds: !Ref DBSubnets
      Events:
        TCTaxis:
          Type: Api
          Properties:
            Path: /request-ride
            Method: post
  TCUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tc_users/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          db_user: !Ref DBUser
          db_pass: !Ref DBPass
          db_endpoint: !Ref DBEndPoint
      VpcConfig:
          SecurityGroupIds: !Ref DBSecurityGroups
          SubnetIds: !Ref DBSubnets
      Events:        
        TCGetUsers:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
        TCGetAllUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
        TCPostUsers:
          Type: Api
          Properties:
            Path: /users
            Method: post
        TCDeleteUsers:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: delete
        TCPatchUsers:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: patch

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TCGeocoderApi:
    Description: "API Gateway endpoint URL for Prod stage for Geocoder function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/geocoder/"
  TCGeocoderFunction:
    Description: "Geocoder Lambda Function ARN"
    Value: !GetAtt TCGeocoderFunction.Arn
  TCGeocoderFunctionIamRole:
    Description: "Implicit IAM Role created for Geocoder function"
    Value: !GetAtt TCGeocoderFunctionRole.Arn

  TCDirectionsApi:
    Description: "API Gateway endpoint URL for Prod stage for Directions function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/directions/"
  TCDirectionsFunction:
    Description: "Directions Lambda Function ARN"
    Value: !GetAtt TCDirectionsFunction.Arn
  TCDirectionsFunctionIamRole:
    Description: "Implicit IAM Role created for Directions function"
    Value: !GetAtt TCDirectionsFunctionRole.Arn

  TCTaxisApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Taxis function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/taxi/"
  TCTaxisFunction:
    Description: "Get Taxis Lambda Function ARN"
    Value: !GetAtt TCTaxisFunction.Arn
  TCTaxisFunctionIamRole:
    Description: "Implicit IAM Role created for Get Taxis function"
    Value: !GetAtt TCTaxisFunctionRole.Arn

  TCRequestRideApi:
    Description: "API Gateway endpoint URL for Prod stage for Requesting Taxis for ride"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/request-ride/"
  TCRequestRideFunction:
    Description: "Get Request Ride Lambda Function ARN"
    Value: !GetAtt TCRequestRideFunction.Arn
  TCRequestRideFunctionIamRole:
    Description: "Implicit IAM Role created for Request Ride function"
    Value: !GetAtt TCRequestRideFunctionRole.Arn
  TCUserFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Creating, Retrieving and Deleting User"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  TCUserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt TCUserFunction.Arn
  TCUserFunctionIamRole:
    Description: "Implicit IAM Role created for User function"
    Value: !GetAtt TCUserFunctionRole.Arn

